import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Settings = { product_name: string; support_email: string; default_locale: string; signup_policy: "open" | "invite-only" };
const defaults: Settings = { product_name: "Cloudflare AI Starter", support_email: "", default_locale: "en", signup_policy: "open" };

export function AdminPlatformSettings() {
  const [settings, setSettings] = useState(defaults); const [saved, setSaved] = useState(defaults); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { const response = await fetch("/api/admin/platform-settings", { credentials: "include" }); const body = await response.json() as { data?: Settings; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || "Unable to load platform settings."); setSettings(body.data); setSaved(body.data); };
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, []);
  const save = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/admin/platform-settings", { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json() as { data?: Settings; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || "Unable to save platform settings."); setSettings(body.data); setSaved(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
  return <section className="operations-card admin-platform-settings"><header><span>Platform-owned configuration</span><h3>Settings</h3><p>Public product identity and signup policy. Secrets and Provider credentials remain local Setup concerns.</p></header>{error ? <p className="operations-error" role="alert">{error}</p> : null}<div className="admin-settings-grid"><label><span>Product name</span><Input value={settings.product_name} onChange={(event) => setSettings({ ...settings, product_name: event.target.value })} /></label><label><span>Support email</span><Input type="email" value={settings.support_email} onChange={(event) => setSettings({ ...settings, support_email: event.target.value })} /></label><label><span>Default locale</span><select value={settings.default_locale} onChange={(event) => setSettings({ ...settings, default_locale: event.target.value })}><option value="en">English</option><option value="fr">French</option><option value="zh-CN">Chinese (Simplified)</option></select></label><label><span>Signup policy</span><select value={settings.signup_policy} onChange={(event) => setSettings({ ...settings, signup_policy: event.target.value as Settings["signup_policy"] })}><option value="open">Open registration</option><option value="invite-only">Invite only</option></select></label></div><Button type="button" disabled={busy || JSON.stringify(settings) === JSON.stringify(saved)} onClick={() => void save()}><Save size={14} />Save settings</Button></section>;
}
