import { useEffect, useState } from "react";
import { Pause, Play, RefreshCw, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export type AdminSaasResource = "organizations" | "subscriptions" | "entitlements" | "usage" | "api-keys" | "webhooks" | "onboarding";
type DirectoryPayload = { available: boolean; columns: string[]; rows: Array<Record<string, unknown>>; total: number };
const labels: Record<AdminSaasResource, string> = { organizations: "Organizations", subscriptions: "Plans & subscriptions", entitlements: "Entitlements", usage: "Usage", "api-keys": "API keys", webhooks: "Webhooks", onboarding: "Onboarding" };
const valueText = (value: unknown) => value === null || value === undefined || value === "" ? "—" : typeof value === "boolean" ? value ? "Yes" : "No" : typeof value === "object" ? JSON.stringify(value) : String(value);
const rowKey = (resource: AdminSaasResource, row: Record<string, unknown>) => resource === "entitlements" ? `${row.plan_id}|${row.feature_key}` : String(row.id || row.user_id || row.owner_user_id || "");

export function AdminSaasDirectory({ resource }: { resource: AdminSaasResource }) {
  const [payload, setPayload] = useState<DirectoryPayload | null>(null); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/saas-directory/${resource}`, { credentials: "include" }); const body = await response.json() as { data?: DirectoryPayload; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || `Unable to load ${labels[resource]}.`); setPayload(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [resource]);
  useEffect(() => { setSelected(null); }, [resource]);
  const mutate = async (action: string) => { if (!selected) return; setBusy(true); setError(""); try { const response = await fetch(`/api/admin/saas-directory/${resource}/${encodeURIComponent(rowKey(resource, selected))}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || "Unable to apply Admin action."); await load(); setSelected(null); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
  const rows = (payload?.rows || []).filter((row) => !query.trim() || Object.values(row).some((value) => valueText(value).toLowerCase().includes(query.trim().toLowerCase())));
  const action = selected && (resource === "subscriptions" ? String(selected.status) === "paused" ? ["activate", "Activate", Play] : ["pause", "Pause", Pause] : resource === "entitlements" ? [selected.enabled ? "disable" : "enable", selected.enabled ? "Disable" : "Enable", selected.enabled ? Pause : Play] : resource === "api-keys" || resource === "webhooks" ? [selected.enabled ? "disable" : "enable", selected.enabled ? "Disable" : "Enable", selected.enabled ? Pause : Play] : resource === "onboarding" ? ["reset", "Reset onboarding", RotateCcw] : null) as [string, string, typeof Play] | null;
  const ActionIcon = action?.[2];
  return <><section className="operations-card admin-saas-directory"><header><div><span>SaaS operations</span><h3>{labels[resource]}</h3><p>{payload?.available ? `${payload.total} records` : "This Pack is not selected in the current project."}</p></div><Button type="button" size="sm" variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw size={14} />Refresh</Button></header>{error ? <p className="operations-error" role="alert">{error}</p> : null}{payload?.available ? <><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${labels[resource].toLowerCase()}`} aria-label={`Search ${labels[resource]}`} /><div className="admin-directory-table" role="table" aria-label={labels[resource]}><div role="row" className="admin-directory-head">{payload.columns.map((column) => <span role="columnheader" key={column}>{column.replaceAll("_", " ")}</span>)}</div>{rows.map((row, index) => <button type="button" role="row" key={rowKey(resource, row) || String(index)} onClick={() => setSelected(row)}>{payload.columns.map((column) => <span role="cell" key={column} title={valueText(row[column])}>{valueText(row[column])}</span>)}</button>)}{!loading && !rows.length ? <p className="admin-user-loading">No matching records.</p> : null}</div></> : null}</section>{selected ? <><button type="button" className="admin-detail-scrim" aria-label={`Close ${labels[resource]} details`} onClick={() => setSelected(null)} /><aside className="operations-card admin-saas-detail" aria-label={`${labels[resource]} details`}><header><div><span>SaaS record</span><h3>{labels[resource]}</h3></div><Button type="button" size="icon" variant="ghost" aria-label={`Close ${labels[resource]} details`} onClick={() => setSelected(null)}><X size={16} /></Button></header><dl>{Object.entries(selected).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{valueText(value)}</dd></div>)}</dl>{action ? <Button type="button" variant="outline" disabled={busy} onClick={() => void mutate(action[0])}>{ActionIcon ? <ActionIcon size={14} /> : null}{action[1]}</Button> : <p className="admin-detail-note">This resource is evidence-only here. Use its owned workspace flow for mutations.</p>}</aside></> : null}</>;
}
