export function renderDesignCSS(profile) {
  const { light, dark } = profile.semanticColors;
  const { radius, motion, fontUi, fontDisplay, fontMono } = profile.tokens;
  const mode = (colors) =>
    [
      `  --design-background: ${colors.background};`,
      `  --design-surface: ${colors.surface};`,
      `  --design-surface-strong: color-mix(in srgb, ${colors.surface} 82%, ${colors.background});`,
      `  --design-foreground: ${colors.foreground};`,
      `  --design-muted: ${colors.muted};`,
      `  --design-accent: ${colors.accent};`,
      `  --design-on-accent: ${colors.onAccent};`,
      `  --design-border: ${colors.border};`,
      `  --design-danger: ${colors.danger};`,
      "  --canvas: var(--design-background);",
      "  --surface: var(--design-surface);",
      "  --surface-soft: var(--design-surface-strong);",
      "  --text: var(--design-foreground);",
      "  --muted: var(--design-muted);",
      "  --subtle: color-mix(in srgb, var(--design-muted) 76%, var(--design-background));",
      "  --border: var(--design-border);",
      "  --strong: color-mix(in srgb, var(--design-border) 58%, var(--design-foreground));",
      "  --accent: var(--design-accent);",
      "  --accent-soft: color-mix(in srgb, var(--design-accent) 12%, var(--design-background));",
      "  --danger: var(--design-danger);",
      "  --sl-color-accent-low: color-mix(in srgb, var(--design-accent) 14%, var(--design-background));",
      "  --sl-color-accent: var(--design-accent);",
      "  --sl-color-accent-high: color-mix(in srgb, var(--design-accent) 36%, var(--design-foreground));",
      "  --sl-color-white: var(--design-foreground);",
      "  --sl-color-gray-1: color-mix(in srgb, var(--design-foreground) 92%, var(--design-background));",
      "  --sl-color-gray-2: color-mix(in srgb, var(--design-foreground) 78%, var(--design-background));",
      "  --sl-color-gray-3: var(--design-muted);",
      "  --sl-color-gray-4: color-mix(in srgb, var(--design-border) 78%, var(--design-foreground));",
      "  --sl-color-gray-5: var(--design-border);",
      "  --sl-color-gray-6: var(--design-surface-strong);",
      "  --sl-color-black: var(--design-background);",
    ].join("\n");
  return [
    "/* Generated by scripts/materialize-blueprint.mjs. Do not edit by hand. */",
    `/* ${profile.id}@${profile.version} */`,
    ":root {",
    `  --design-profile: ${JSON.stringify(profile.id)};`,
    `  --design-font-ui: ${fontUi};`,
    `  --design-font-display: ${fontDisplay};`,
    `  --design-font-mono: ${fontMono};`,
    `  --design-radius-sm: ${radius.sm}px;`,
    `  --design-radius-md: ${radius.md}px;`,
    `  --design-radius-lg: ${radius.lg}px;`,
    `  --design-motion-fast: ${motion.fastMs}ms;`,
    `  --design-motion-standard: ${motion.standardMs}ms;`,
    "  --sl-font: var(--design-font-ui);",
    "  --radius-sm: var(--design-radius-sm);",
    "  --radius-md: var(--design-radius-md);",
    "  --radius-lg: var(--design-radius-lg);",
    mode(light),
    "}",
    ':root[data-theme="dark"] {',
    mode(dark),
    "}",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    mode(dark),
    "  }",
    "}",
    "",
  ].join("\n");
}

export function renderMobileDesign(profile) {
  return [
    "// Generated by scripts/materialize-blueprint.mjs. Do not edit by hand.",
    `export const generatedMobileDesign = ${JSON.stringify({ profileId: profile.id, version: profile.version, light: profile.semanticColors.light, dark: profile.semanticColors.dark, fonts: { ui: profile.tokens.fontMobileUi, display: profile.tokens.fontMobileDisplay }, radius: profile.tokens.radius, motion: profile.tokens.motion }, null, 2)} as const;`,
    "",
  ].join("\n");
}

function renderStyleKitMode(colors, elevation) {
  return [
    `  --design-background: ${colors.background};`,
    `  --design-surface: ${colors.surface};`,
    `  --design-surface-strong: ${colors.surfaceStrong};`,
    `  --design-foreground: ${colors.foreground};`,
    `  --design-muted: ${colors.muted};`,
    `  --design-accent: ${colors.accent};`,
    `  --design-on-accent: ${colors.onAccent};`,
    `  --design-border: ${colors.border};`,
    `  --design-danger: ${colors.danger};`,
    `  --design-highlight: ${colors.highlight};`,
    `  --design-shadow-color: ${colors.shadow};`,
    `  --design-shadow-raised: ${elevation.raised};`,
    `  --design-shadow-raised-large: ${elevation.raisedLarge};`,
    `  --design-shadow-recessed: ${elevation.recessed};`,
    `  --design-shadow-pressed: ${elevation.pressed};`,
    "  --canvas: var(--design-background);",
    "  --surface: var(--design-surface);",
    "  --surface-soft: var(--design-surface-strong);",
    "  --text: var(--design-foreground);",
    "  --muted: var(--design-muted);",
    "  --subtle: var(--design-muted);",
    "  --border: var(--design-border);",
    "  --strong: color-mix(in srgb, var(--design-border) 58%, var(--design-foreground));",
    "  --accent: var(--design-accent);",
    "  --accent-soft: color-mix(in srgb, var(--design-accent) 12%, var(--design-background));",
    "  --danger: var(--design-danger);",
    "  --sl-color-accent-low: color-mix(in srgb, var(--design-accent) 14%, var(--design-background));",
    "  --sl-color-accent: var(--design-accent);",
    "  --sl-color-accent-high: color-mix(in srgb, var(--design-accent) 36%, var(--design-foreground));",
    "  --sl-color-white: var(--design-foreground);",
    "  --sl-color-gray-1: color-mix(in srgb, var(--design-foreground) 92%, var(--design-background));",
    "  --sl-color-gray-2: color-mix(in srgb, var(--design-foreground) 78%, var(--design-background));",
    "  --sl-color-gray-3: var(--design-muted);",
    "  --sl-color-gray-4: color-mix(in srgb, var(--design-border) 78%, var(--design-foreground));",
    "  --sl-color-gray-5: var(--design-border);",
    "  --sl-color-gray-6: var(--design-surface-strong);",
    "  --sl-color-black: var(--design-background);",
  ].join("\n");
}

export function renderStyleKitCSS(snapshot) {
  const web = snapshot.adapterTokens?.web;
  if (
    !web?.semanticColors?.light ||
    !web?.semanticColors?.dark ||
    !web?.elevation?.light ||
    !web?.elevation?.dark
  )
    throw new Error(
      `StyleKit snapshot ${snapshot.style?.slug || "<missing>"} does not contain complete Web adapter tokens`,
    );
  return [
    "/* Generated by scripts/materialize-blueprint.mjs. Do not edit by hand. */",
    `/* StyleKit ${snapshot.style.slug}@${snapshot.snapshotVersion} from ${snapshot.provenance.revision} */`,
    ":root {",
    `  --design-profile: ${JSON.stringify(`stylekit-${snapshot.style.slug}`)};`,
    `  --design-stylekit-revision: ${JSON.stringify(snapshot.provenance.revision)};`,
    `  --design-font-ui: ${web.typography.ui};`,
    `  --design-font-display: ${web.typography.display};`,
    `  --design-font-mono: ${web.typography.mono};`,
    `  --design-radius-sm: ${web.radius.sm}px;`,
    `  --design-radius-md: ${web.radius.md}px;`,
    `  --design-radius-lg: ${web.radius.lg}px;`,
    `  --design-motion-fast: ${web.motion.fastMs}ms;`,
    `  --design-motion-standard: ${web.motion.standardMs}ms;`,
    `  --stylekit-family: ${JSON.stringify(web.family?.id || snapshot.style.adapterFamily)};`,
    `  --stylekit-border-width: ${web.family?.borderWidth ?? 1}px;`,
    `  --stylekit-texture: ${JSON.stringify(web.family?.texture || "none")};`,
    "  --sl-font: var(--design-font-ui);",
    "  --radius-sm: var(--design-radius-sm);",
    "  --radius-md: var(--design-radius-md);",
    "  --radius-lg: var(--design-radius-lg);",
    renderStyleKitMode(web.semanticColors.light, web.elevation.light),
    "}",
    ':root[data-theme="dark"] {',
    renderStyleKitMode(web.semanticColors.dark, web.elevation.dark),
    "}",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    renderStyleKitMode(web.semanticColors.dark, web.elevation.dark),
    "  }",
    "}",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root { --design-motion-fast: 0ms; --design-motion-standard: 0ms; }",
    "}",
    "",
  ].join("\n");
}

export function renderStyleKitMobile(snapshot) {
  const mobile = snapshot.adapterTokens?.mobile;
  const web = snapshot.adapterTokens?.web;
  if (!mobile)
    throw new Error(
      `StyleKit snapshot ${snapshot.style?.slug || "<missing>"} does not contain Mobile adapter tokens`,
    );
  if (!web?.semanticColors?.light || !web?.semanticColors?.dark)
    throw new Error(
      `StyleKit snapshot ${snapshot.style?.slug || "<missing>"} cannot complete the Mobile semantic color contract`,
    );
  const normalizedMobile = {
    ...mobile,
    light: { ...web.semanticColors.light, ...mobile.light },
    dark: { ...web.semanticColors.dark, ...mobile.dark },
    fonts: mobile.fonts || { ui: "System", display: "System" },
  };
  return [
    "// Generated by scripts/materialize-blueprint.mjs. Do not edit by hand.",
    `export const generatedMobileDesign = ${JSON.stringify({ profileId: `stylekit-${snapshot.style.slug}`, version: snapshot.snapshotVersion, sourceRevision: snapshot.provenance.revision, ...normalizedMobile }, null, 2)} as const;`,
    "",
  ].join("\n");
}

const sharedInteractionAdapter = `
:where(button, a, input, textarea, select):focus-visible {
  outline: 3px solid color-mix(in srgb, var(--design-accent) 38%, transparent);
  outline-offset: 3px;
}
`;

const neutralTargetAdapters = {
  web: `
body { background: var(--design-background); }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .operations-card,
.notification-popover, .notification-center, .account-menu, .saas-dashboard-card, .saas-workspace-menu,
.settings-panel, .saas-search-results, .snapshot-state, .stylekit-pinned) {
  color: var(--design-foreground);
  border-color: var(--design-border);
  background: var(--design-surface);
}
:where(.primary-action, .save-blueprint) { color: var(--design-on-accent); background: var(--design-accent); }
:where(.field input, .setup-field input, .setup-field textarea, .setup-field select, .provider-panel select,
.preset-selector select, .ticket-form textarea, .admin-list select, .saas-search input) {
  color: var(--design-foreground);
  border-color: var(--design-border);
  background: var(--design-surface);
}
`,
  marketing: `
body { background: var(--design-background); }
:where(.assembly-receipt, .proof-band, .outcome-list article, .cta-section, .empty-state,
.growth-card, .role-list > a, .detail-outcomes > div, .detail-unavailable) {
  color: var(--design-foreground);
  border-color: var(--design-border);
  background: var(--design-surface);
}
:where(.header-action, .primary-button) { color: var(--design-on-accent); background: var(--design-accent); }
`,
  docs: `
body { color: var(--design-foreground); background: var(--design-background); }
:where(.header, header.header, .sidebar-pane, .right-sidebar-panel) {
  border-color: var(--design-border) !important;
  background: var(--design-background) !important;
}
:where(.card, .sl-link-card, .expressive-code, .starlight-aside, input, select, textarea, .search-input) {
  border-color: var(--design-border) !important;
  background: var(--design-surface) !important;
}
:where(button[data-open-modal], select) {
  color: var(--design-foreground) !important;
}
:where(:not(pre) > code, kbd) {
  color: var(--design-foreground) !important;
  background: var(--design-shadow-color) !important;
}
`,
};

const neumorphismWebAdapter = `
/* StyleKit owned Web adapter: soft depth is semantic, never decorative noise. */
.home-grid, .auth-shell { background-image: none; }
.brand > span, .auth-brand > span, .saas-brand-mark {
  color: var(--design-on-accent);
  background: var(--design-accent);
  box-shadow: var(--design-shadow-raised);
}
.plan-nav, .plan-toolbar, .product-header, .setup-header, .saas-sidebar, .saas-topbar {
  border-color: transparent;
  background: var(--design-background);
}
.plan-nav, .saas-sidebar { box-shadow: 5px 0 14px color-mix(in srgb, var(--design-shadow-color) 52%, transparent); }
.plan-toolbar, .product-header, .setup-header, .saas-topbar { box-shadow: 0 5px 14px color-mix(in srgb, var(--design-shadow-color) 42%, transparent); }
.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .operations-card,
.notification-popover, .notification-center, .account-menu, .saas-dashboard-card, .saas-workspace-menu, .settings-panel,
.saas-search-results, .snapshot-state, .stylekit-pinned {
  border-color: transparent;
  background: var(--design-surface);
  box-shadow: var(--design-shadow-raised-large);
}
.surface, .setup-panel, .operations-card, .saas-dashboard-card { border-radius: var(--design-radius-lg); }
.notification-popover, .notification-center, .account-menu, .saas-workspace-menu, .saas-search-results { border-radius: var(--design-radius-md); }
.lifecycle-surface, .catalog-table, .module-table { box-shadow: var(--design-shadow-recessed); }
.lifecycle-table thead th, .catalog-header, .module-header, .lifecycle-heading { background: transparent; }
.primary-action, .button, .theme-button, .menu-button, .nav-head button, .notification-trigger,
.account-trigger, .saas-icon-button, .saas-workspace-trigger, .save-blueprint,
.kind-picker button, .segmented-control button, .setup-steps button, .profile-choice, .pack-choice {
  border-color: transparent;
  border-radius: var(--design-radius-md);
  background: var(--design-surface);
  box-shadow: var(--design-shadow-raised);
  transition: box-shadow var(--design-motion-fast) ease, transform var(--design-motion-fast) ease, color var(--design-motion-fast) ease;
}
.primary-action, .save-blueprint {
  color: var(--design-on-accent);
  background: var(--design-accent);
}
.primary-action:hover, .save-blueprint:hover { background: var(--design-accent); box-shadow: 4px 4px 8px var(--design-shadow-color), -4px -4px 8px var(--design-highlight); }
.primary-action:active, .button:active, .theme-button:active, .menu-button:active, .nav-head button:active,
.notification-trigger:active, .account-trigger:active, .saas-icon-button:active, .saas-workspace-trigger:active,
.save-blueprint:active, .kind-picker button:active, .segmented-control button:active, .setup-steps button:active,
.profile-choice:active, .pack-choice:active { transform: none; box-shadow: var(--design-shadow-pressed); }
.plan-nav nav a[aria-current="page"], .saas-nav-link[aria-current="page"], .product-header nav a[aria-current="page"],
.segmented-control button[aria-pressed="true"], .kind-picker button[aria-pressed="true"], .setup-steps button.active,
.profile-choice.selected, .pack-choice.selected {
  border-color: transparent;
  color: var(--design-accent);
  background: var(--design-surface);
  box-shadow: var(--design-shadow-pressed);
}
.plan-nav nav a:hover, .saas-nav-link:hover, .product-header nav a:hover { background: var(--design-surface); box-shadow: var(--design-shadow-raised); }
.field input, .setup-field input, .setup-field textarea, .setup-field select, .provider-panel select,
.preset-selector select, .ticket-form textarea, .admin-list select, .saas-search input {
  border-color: transparent;
  border-radius: var(--design-radius-md);
  background: var(--design-surface);
  box-shadow: var(--design-shadow-recessed);
  transition: box-shadow var(--design-motion-fast) ease;
}
.field input:focus, .setup-field input:focus, .setup-field textarea:focus, .setup-field select:focus,
.provider-panel select:focus, .preset-selector select:focus, .ticket-form textarea:focus,
.admin-list select:focus, .saas-search input:focus {
  border-color: transparent;
  box-shadow: inset 6px 6px 12px var(--design-shadow-color), inset -6px -6px 12px var(--design-highlight);
}
.notification-item, .catalog-row, .module-row, .ticket-list article, .admin-list article,
.compact-facts div, .binding-list div, .environment-grid dl div, .document-list > div,
.notification-popover > header, .notification-center-toolbar, .notification-all {
  border-color: color-mix(in srgb, var(--design-border) 54%, transparent);
}
.status, .ticket-kind, .notification-badge { box-shadow: var(--design-shadow-recessed); }
.notification-item:hover, .notification-item:focus-visible { background: transparent; box-shadow: var(--design-shadow-recessed); }
.saas-product-slot, .saas-dashboard-empty, .operations-empty { background: transparent; }
@media (max-width: 980px) {
  .plan-nav.open, .saas-sidebar.open { box-shadow: var(--design-shadow-raised-large); }
}
`;

const neumorphismMarketingAdapter = `
/* StyleKit owned marketing adapter: spacious composition with selective soft depth. */
.site-header, .site-footer, .workflow-section, .page-intro, .content-section + .content-section { border-color: transparent; }
.site-header { margin-top: 14px; padding: 0 18px; border-radius: var(--design-radius-lg); box-shadow: var(--design-shadow-raised); }
.header-action, .primary-button, .secondary-button {
  border-color: transparent;
  box-shadow: var(--design-shadow-raised);
  transition: box-shadow var(--design-motion-fast) ease, transform var(--design-motion-fast) ease;
}
.header-action, .primary-button { color: var(--design-on-accent); background: var(--design-accent); }
.secondary-button { color: var(--design-foreground); background: var(--design-surface); }
.header-action:hover, .primary-button:hover, .secondary-button:hover { box-shadow: 4px 4px 8px var(--design-shadow-color), -4px -4px 8px var(--design-highlight); }
.header-action:active, .primary-button:active, .secondary-button:active { transform: none; box-shadow: var(--design-shadow-pressed); }
.assembly-receipt, .proof-band, .outcome-list article, .cta-section, .empty-state,
.growth-card, .role-list > a, .detail-outcomes > div, .detail-unavailable {
  border-color: transparent;
  border-radius: var(--design-radius-lg);
  background: var(--design-surface);
  box-shadow: var(--design-shadow-raised-large);
}
.assembly-receipt header { border-color: transparent; background: transparent; }
.assembly-receipt dl div, .workflow-section li, .fact-list div { border-color: color-mix(in srgb, var(--design-border) 52%, transparent); }
.proof-band { gap: 1px; padding: 10px; border: 0; }
.proof-band span + span { border-left: 1px solid color-mix(in srgb, var(--design-border) 52%, transparent); }
.outcome-list { gap: 22px; padding: 0; background: transparent; }
.outcome-list article:nth-child(3n + 1) { background: var(--design-surface); }
.cta-section { background: var(--design-surface); }
.growth-tags span, .availability { box-shadow: var(--design-shadow-recessed); }
.growth-card:hover, .role-list > a:hover { box-shadow: 10px 10px 20px var(--design-shadow-color), -10px -10px 20px var(--design-highlight); }
@media (max-width: 760px) {
  .site-header { width: min(100% - 24px, 1180px); }
  .proof-band span:nth-child(odd) { border-left: 0; }
}
`;

const neumorphismDocsAdapter = `
/* StyleKit owned Starlight adapter. Documentation favors reading density over ornamental depth. */
body { background: var(--design-background); }
:where(.header, header.header, .sidebar-pane, .right-sidebar-panel) {
  border-color: transparent !important;
  background: var(--design-background) !important;
}
:where(.header, header.header) { box-shadow: 0 5px 14px color-mix(in srgb, var(--design-shadow-color) 42%, transparent); }
:where(.sidebar-pane) { box-shadow: 5px 0 14px color-mix(in srgb, var(--design-shadow-color) 42%, transparent); }
:where(.card, .sl-link-card, .expressive-code, .starlight-aside) {
  border-color: transparent !important;
  border-radius: var(--design-radius-lg) !important;
  background: var(--design-surface) !important;
  box-shadow: var(--design-shadow-raised) !important;
}
:where(input, select, textarea, .search-input) {
  border-color: transparent !important;
  border-radius: var(--design-radius-md) !important;
  background: var(--design-surface) !important;
  box-shadow: var(--design-shadow-recessed) !important;
}
:where(.sidebar-content a[aria-current="page"], .tablist-wrapper a[aria-selected="true"]) {
  border-color: transparent !important;
  color: var(--design-accent) !important;
  background: var(--design-surface) !important;
  box-shadow: var(--design-shadow-pressed) !important;
}
`;

export function renderStyleKitAdapterCSS(snapshot, target) {
  const neumorphismTargets = {
    web: neumorphismWebAdapter,
    marketing: neumorphismMarketingAdapter,
    docs: neumorphismDocsAdapter,
  };
  const targetCss =
    snapshot.style?.slug === "neumorphism"
      ? neumorphismTargets[target]
      : neutralTargetAdapters[target];
  if (!targetCss) throw new Error(`Unknown StyleKit adapter target ${target}`);
  const family = snapshot.style?.adapterFamily;
  const familyCss = {
    flat: `
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border: var(--stylekit-border-width) solid var(--design-border) !important; box-shadow: none !important; }
:where(button, .button, .primary-action, .secondary-button, input, textarea, select) { box-shadow: none !important; border: var(--stylekit-border-width) solid var(--design-border) !important; }
`,
    editorial: `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); letter-spacing: -0.035em; }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 0 !important; border-top: var(--stylekit-border-width) solid var(--design-foreground) !important; box-shadow: none !important; }
:where(button, .button, .primary-action, .secondary-button) { border-radius: var(--design-radius-sm) !important; box-shadow: none !important; }
`,
    "soft-depth": `
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border-color: transparent !important; }
`,
    "hard-shadow": `
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card, button, .button, input, textarea, select) { border: var(--stylekit-border-width) solid var(--design-foreground) !important; }
:where(button, .button, .primary-action, .secondary-button):active { transform: translate(3px, 3px) !important; }
:where(h1, h2, h3) { font-weight: 850; letter-spacing: -0.045em; }
`,
    glass: `
body { background-image: radial-gradient(circle at 8% 4%, color-mix(in srgb, var(--design-accent) 30%, transparent), transparent 38%), radial-gradient(circle at 92% 20%, color-mix(in srgb, var(--design-surface-strong) 70%, transparent), transparent 42%); background-attachment: fixed; }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card, .site-header, .saas-topbar) { background: color-mix(in srgb, var(--design-surface) 72%, transparent) !important; border: 1px solid color-mix(in srgb, var(--design-highlight) 58%, transparent) !important; backdrop-filter: blur(18px) saturate(135%); }
`,
    gradient: `
body { background-image: radial-gradient(circle at 10% 0%, color-mix(in srgb, var(--design-accent) 18%, transparent), transparent 34%), radial-gradient(circle at 90% 14%, color-mix(in srgb, var(--design-surface-strong) 82%, transparent), transparent 38%); background-attachment: fixed; }
:where(.primary-action, .header-action, .save-blueprint, .brand > span, .auth-brand > span) { background-image: linear-gradient(135deg, var(--design-accent), color-mix(in srgb, var(--design-accent) 54%, var(--design-foreground))) !important; }
`,
    "dark-neon": `
body { background-image: linear-gradient(color-mix(in srgb, var(--design-accent) 7%, transparent) 1px, transparent 1px), linear-gradient(90deg, color-mix(in srgb, var(--design-accent) 7%, transparent) 1px, transparent 1px); background-size: 32px 32px; }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid color-mix(in srgb, var(--design-accent) 46%, var(--design-border)) !important; }
:where(h1, h2, h3, code) { text-shadow: 0 0 18px color-mix(in srgb, var(--design-accent) 24%, transparent); }
`,
    organic: `
body { background-image: radial-gradient(circle at 0 0, color-mix(in srgb, var(--design-accent) 8%, transparent), transparent 30%); background-attachment: fixed; }
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); font-weight: 600; letter-spacing: -0.025em; }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid color-mix(in srgb, var(--design-border) 72%, transparent) !important; }
`,
    ornamental: `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); letter-spacing: -0.02em; }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid color-mix(in srgb, var(--design-accent) 38%, var(--design-border)) !important; outline: 1px solid color-mix(in srgb, var(--design-accent) 12%, transparent); outline-offset: -5px; }
`,
    dense: `
:where(body, button, input, textarea, select) { font-family: var(--design-font-ui); }
:where(.surface, .auth-card, .setup-panel, .pack-choice, .profile-choice, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid var(--design-border) !important; box-shadow: var(--design-shadow-raised) !important; }
:where(h1, h2, h3, .status, .ticket-kind) { letter-spacing: -0.015em; }
`,
  }[family];
  if (!familyCss)
    throw new Error(
      `No owned adapter family is registered for StyleKit ${snapshot.style?.slug || "<missing>"}: ${family || "<missing>"}`,
    );
  const styleSignatureCss = {
    "neo-brutalist": `
:where(h1, h2, h3, .hero h1, .page-intro h1) { font-weight: 900; letter-spacing: -0.055em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-width: 3px !important; box-shadow: 7px 7px 0 var(--design-foreground) !important; }
`,
    editorial: `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); font-weight: 520; letter-spacing: -0.045em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-width: 1px 0 0 !important; border-radius: 0 !important; }
`,
    "corporate-clean": `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-ui); font-weight: 680; letter-spacing: -0.035em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid var(--design-border) !important; border-radius: 10px !important; box-shadow: none !important; }
`,
    glassmorphism: `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-color: var(--design-highlight) !important; border-radius: 24px !important; box-shadow: var(--design-shadow-raised-large) !important; }
`,
    "art-deco": `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); text-align: center; text-transform: uppercase; letter-spacing: 0.12em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 4px double var(--design-accent) !important; border-radius: 0 !important; }
`,
    bauhaus: `
:where(h1, h2, h3, .hero h1, .page-intro h1) { font-family: var(--design-font-ui); font-weight: 900; letter-spacing: -0.06em; text-transform: lowercase; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 3px solid var(--design-foreground) !important; border-radius: 0 var(--design-radius-lg) 0 0 !important; box-shadow: none !important; }
`,
    skeuomorphism: `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid var(--design-highlight) !important; box-shadow: var(--design-shadow-raised-large) !important; }
:where(button, .button, .primary-action, .secondary-button, input, textarea, select) { border: 1px solid var(--design-border) !important; box-shadow: var(--design-shadow-raised) !important; }
`,
    risograph: `
:where(h1, h2, .hero h1, .page-intro h1) { font-weight: 820; letter-spacing: -0.045em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 2px solid var(--design-foreground) !important; outline: 2px solid var(--design-accent); outline-offset: 3px; border-radius: 1px !important; box-shadow: none !important; }
`,
    "developer-terminal": `
:where(body, button, input, textarea, select, h1, h2, h3) { font-family: var(--design-font-mono); }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid var(--design-accent) !important; border-radius: 2px !important; box-shadow: none !important; }
`,
    "soft-utility": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid var(--design-border) !important; border-radius: 8px !important; box-shadow: none !important; }
:where(button, .button, .primary-action, .secondary-button, input, textarea, select) { border-radius: 6px !important; box-shadow: none !important; }
`,
    "japanese-fresh": `
:where(h1, h2, .hero h1, .page-intro h1) { font-weight: 520; letter-spacing: -0.045em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-top-width: 3px !important; }
`,
    "wabi-sabi": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-radius: 24px 8px 20px 11px !important; }
:where(button, .button, .primary-action, .secondary-button) { border-radius: 12px 4px 10px 6px !important; }
`,
    "kawaii-minimal": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-radius: 28px !important; }
:where(button, .button, .primary-action, .secondary-button, input, textarea, select) { border-radius: 999px !important; }
`,
    "ink-wash": `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); font-weight: 500; letter-spacing: 0.01em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-width: 0 0 1px !important; border-radius: 0 !important; box-shadow: none !important; }
`,
    "ukiyo-e-digital": `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); font-weight: 780; letter-spacing: -0.035em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-width: 1px 1px 1px 5px !important; border-left-color: var(--design-accent) !important; border-radius: 2px !important; }
`,
    "cyber-wafuu": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 3px double var(--design-accent) !important; outline: 1px solid var(--design-border); outline-offset: -7px; }
:where(h1, h2, .hero h1, .page-intro h1) { letter-spacing: 0.025em; }
`,
    "cyber-chinese": `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); letter-spacing: 0.045em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 1px solid var(--design-accent) !important; outline: 1px solid var(--design-border); outline-offset: -5px; border-radius: 0 !important; }
`,
    "islamic-geometric": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 3px double var(--design-accent) !important; border-radius: 0 var(--design-radius-lg) 0 var(--design-radius-lg) !important; }
:where(h1, h2, .hero h1, .page-intro h1) { text-align: center; letter-spacing: 0.02em; }
`,
    "indian-festive": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 2px solid var(--design-accent) !important; outline: 1px solid var(--design-border); outline-offset: -7px; border-radius: 28px 28px 8px 8px !important; }
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); font-weight: 760; }
`,
    "african-textile": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 3px solid var(--design-foreground) !important; border-block-start-color: var(--design-accent) !important; border-radius: 0 !important; }
:where(.surface:nth-child(even), .saas-dashboard-card:nth-child(even), .growth-card:nth-child(even)) { border-inline-start-width: 8px !important; }
`,
    "pixel-art": `
:where(*, *::before, *::after) { border-radius: 0 !important; }
:where(button, .button, .primary-action, .secondary-button) { transition-timing-function: steps(2, end) !important; }
:where(img) { image-rendering: pixelated; }
`,
    y2k: `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-radius: 32px !important; box-shadow: var(--design-shadow-raised-large) !important; }
:where(button, .button, .primary-action, .secondary-button, input, textarea, select) { border-radius: 999px !important; }
`,
    "pop-art": `
:where(h1, h2, h3, .hero h1, .page-intro h1) { font-weight: 900; text-transform: uppercase; letter-spacing: -0.045em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 3px solid var(--design-foreground) !important; box-shadow: 7px 7px 0 var(--design-accent) !important; }
`,
    "frutiger-aero": `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-radius: 34px !important; box-shadow: var(--design-shadow-raised-large) !important; }
:where(button, .button, .primary-action, .secondary-button) { border-radius: 999px !important; box-shadow: var(--design-shadow-raised) !important; }
`,
    "gothic-lolita": `
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); letter-spacing: 0.025em; }
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 4px double var(--design-foreground) !important; outline: 1px solid var(--design-accent); outline-offset: -8px; border-radius: 18px !important; }
`,
    surrealism: `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border-radius: 38px 5px 28px 12px !important; }
:where(.surface:nth-child(even), .saas-dashboard-card:nth-child(even), .growth-card:nth-child(even)) { border-radius: 6px 34px 12px 26px !important; }
`,
    maximalism: `
:where(.surface, .auth-card, .setup-panel, .saas-dashboard-card, .growth-card, .sl-link-card) { border: 3px solid var(--design-accent) !important; outline: 2px solid var(--design-foreground); outline-offset: 4px; }
:where(h1, h2, .hero h1, .page-intro h1) { font-family: var(--design-font-display); font-weight: 850; letter-spacing: -0.05em; }
`,
  }[snapshot.style?.slug];
  return [
    "/* Generated by scripts/materialize-blueprint.mjs. Do not edit by hand. */",
    `/* StyleKit ${snapshot.style.slug}@${snapshot.snapshotVersion} component adapter for ${target}. */`,
    sharedInteractionAdapter.trim(),
    targetCss.trim(),
    `/* Owned ${family} family layer; source-specific tokens remain pinned in the snapshot. */`,
    familyCss.trim(),
    styleSignatureCss
      ? `/* Owned ${snapshot.style.slug} signature layer. */\n${styleSignatureCss.trim()}`
      : `/* ${snapshot.style.slug} relies on its pinned source tokens and ${family} family contract. */`,
    "",
  ].join("\n");
}
