const pickDocument = ({ path, title, status, summary }) => ({ path, title, status, summary });
const pickDocumentIndex = ({ path, title, status }) => ({ path, title, status, summary: "" });
const pickChange = ({ id, path, title, status }) => ({ id, path, title, status, summary: "" });

export function compactDevelopmentPlan(snapshot) {
  return {
    schemaVersion: snapshot.schemaVersion,
    generatedAt: snapshot.generatedAt,
    source: snapshot.source,
    project: snapshot.project,
    technology: snapshot.technology.map(({ area, choice, status }) => ({ area, choice, status })),
    assembly: {
      blueprint: {
        status: snapshot.assembly.blueprint.status,
        preset: snapshot.assembly.blueprint.preset,
        designProfile: snapshot.assembly.blueprint.designProfile,
        stylekit: snapshot.assembly.blueprint.stylekit,
        pageSet: snapshot.assembly.blueprint.pageSet,
        setup: snapshot.assembly.blueprint.setup,
        selections: snapshot.assembly.blueprint.selections,
        providers: snapshot.assembly.blueprint.providers,
      },
      catalog: {
        schemaVersion: snapshot.assembly.catalog.schemaVersion,
        catalogVersion: snapshot.assembly.catalog.catalogVersion,
        policies: snapshot.assembly.catalog.policies,
        presets: snapshot.assembly.catalog.presets,
        packs: snapshot.assembly.catalog.packs.map((pack) => ({
          id: pack.id,
          kind: pack.kind,
          name: pack.name,
          version: pack.version,
          status: pack.status,
          delivery: pack.delivery,
          targets: pack.targets,
          ownership: pack.ownership,
          source: pack.source?.map(({ name, relationship }) => ({ name, relationship })) || [],
          updatePolicy: pack.updatePolicy,
        })),
      },
      designCatalog: {
        schemaVersion: snapshot.assembly.designCatalog.schemaVersion,
        catalogVersion: snapshot.assembly.designCatalog.catalogVersion,
        sourcePolicy: snapshot.assembly.designCatalog.sourcePolicy,
        profiles: snapshot.assembly.designCatalog.profiles.map((profile) => ({
          id: profile.id,
          version: profile.version,
          packId: profile.packId,
          name: profile.name,
          description: profile.description,
          status: profile.status,
          targets: profile.targets,
          dials: profile.dials,
          adapters: profile.adapters,
        })),
      },
      stylekit: {
        source: snapshot.assembly.stylekit.source,
        styleCount: snapshot.assembly.stylekit.styleCount,
        catalogVersion: snapshot.assembly.stylekit.catalogVersion,
        classification: snapshot.assembly.stylekit.classification,
        globalEligibleCount: snapshot.assembly.stylekit.globalEligibleCount,
        selected: snapshot.assembly.stylekit.selected,
        snapshots: snapshot.assembly.stylekit.snapshots.map((style) => ({
          slug: style.slug,
          name: style.name,
          nameEn: style.nameEn,
          snapshotVersion: style.snapshotVersion,
          snapshotHash: style.snapshotHash,
          immutable: style.immutable,
          classification: style.classification,
          globalEligibility: style.globalEligibility,
          targets: style.targets,
          aiRules: style.aiRules,
        })),
      },
      pageCatalog: {
        schemaVersion: snapshot.assembly.pageCatalog.schemaVersion,
        catalogVersion: snapshot.assembly.pageCatalog.catalogVersion,
        policy: snapshot.assembly.pageCatalog.policy,
        pages: snapshot.assembly.pageCatalog.pages.map((page) => ({
          id: page.id,
          packId: page.packId,
          name: page.name,
          route: page.route,
          group: page.group,
          renderer: page.renderer,
          required: page.required,
          defaultSelected: page.defaultSelected,
          status: page.status,
        })),
      },
      materialization: snapshot.assembly.materialization,
    },
    modules: snapshot.modules.map(pickDocument),
    changes: snapshot.changes.map(pickChange),
    documents: snapshot.documents.map(pickDocumentIndex),
    environments: snapshot.environments,
    cloudflare: snapshot.cloudflare,
    orchestration: snapshot.orchestration,
    release: snapshot.release,
    documentation: snapshot.documentation,
  };
}
